version: '3'

services:
    irods-catalog:
        build:
            context: irods_catalog
        # 5432 is exposed by default and can conflict with other postgres containers.
        # When the metalnx-db service is no longer needed, this stanza can be removed.
        ports:
            - "5430:5432"
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-s3:
        build:
            context: irods_catalog_s3
        # 5432 is exposed by default and can conflict with other postgres containers.
        # When the metalnx-db service is no longer needed, this stanza can be removed.
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        depends_on:
            - irods-catalog

    irods-catalog-provider-s3:
        build:
            context: irods_catalog_provider_s3
        depends_on:
            - irods-catalog-s3

    irods-client-icommands:
        build:
            context: irods_client_icommands
        depends_on:
            - irods-catalog-provider

    irods-s3-bridge:
        build:
            context: s3-bridge
        depends_on:
            - irods-catalog-provider
        volumes:
            - ./s3-bridge/demo-config.json:/root/config.json:ro
    minio-client:
        build:
            context: minio-client
        depends_on:
            - irods-s3-bridge
 
    minio:
        image: minio/minio:RELEASE.2022-10-29T06-21-33Z
        command: server --address ":19000" --console-address ":19001" /data
        ports:
            - "19000:19000"
            - "19001:19001"
        volumes:
          - ./minio-data:/data
        environment: 
          MINIO_ROOT_USER: irods
          MINIO_ROOT_PASSWORD: irodsadmin



